version: '3.9'
services:
  backend:
    build: .
    image: 'ghcr.io/bakseter/531/backend:latest'
    # Don't start backend before database is up.
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    ports:
      - '8080:8080'
    environment:
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: '${DB_PASSWORD:?DB_PASSWORD must be set}'
      DATABASE_URL: 'jdbc:postgresql://database:5432/postgres'
      MIGRATE_DB: true

  backend_dev:
    build: .
    image: 'ghcr.io/bakseter/531/backend:latest'
    # Don't start backend before database is up.
    depends_on:
      database:
        condition: service_healthy
    links:
      - database
    ports:
      - '8081:8081'
    environment:
      DATABASE_USERNAME: 'postgres'
      DATABASE_PASSWORD: '${DB_PASSWORD:?DB_PASSWORD must be set}'
      DATABASE_URL: 'jdbc:postgresql://database:5432/postgres'
      DEV_ISSUER: 'http://backend:8081/'
      PORT: 8081
      DEV: true

  database:
    image: postgres:15.1-alpine
    restart: always
    ports:
      - '5432:5432'
    # Check if database is ready.
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: 'postgres'
      DATABASE_PASSWORD: '${DB_PASSWORD:?DB_PASSWORD must be set}'
      POSTGRES_DB: 'postgres'

  caddy:
    image: caddy:2.7.5-alpine
    command:
      [
        'caddy',
        'reverse-proxy',
        '--from',
        'api.bakseter.net',
        '--to',
        'backend:8080',
      ]
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy_data:/data
      - caddy_config:/config

  caddy_dev:
    image: caddy:2.7.5-alpine
    command:
      [
        'caddy',
        'reverse-proxy',
        '--from',
        'api.bakseter.net:8081',
        '--to',
        'backend_dev:8081',
      ]
    ports:
      - '8081:8081'
    volumes:
      - caddy_data_dev:/data
      - caddy_config_dev:/config

volumes:
  caddy_data:
  caddy_config:
  caddy_data_dev:
  caddy_config_dev:
