name: "pnpm install"
description: "Setup pnpm with cache and install dependencies"

inputs:
  node-version:
    required: false
    default: 18
    type: "string"
    description: "Sets the version of Node.js to use."
  pnpm-version:
    required: false
    default: 8
    type: "string"
    description: "Sets the version of pnpm to use."
  working-directory:
    required: false
    default: "."
    type: "string"
    description: "Sets the working directory for pnpm."

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - uses: pnpm/action-setup@v3
      name: Install pnpm
      with:
        version: ${{ inputs.pnpm-version }}
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: Install dependencies
      shell: bash
      run: pnpm i
      working-directory: ${{ inputs.working-directory }}
