name: Build backend & scan image with Trivy

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    - cron: '3 4 * * 5'

jobs:
  docker_build_scan:
    name: "Build with Docker & scan with Trivy"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      IMAGE_NAME: "ghcr.io/${{ github.repository }}/backend"
      TRIVY_SARIF: "trivy-results.sarif"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache
        if: github.event_name == 'pull_request'
        run: |
          cd backend
          docker build \
            --cache-from "$IMAGE_NAME" \
            -t "$IMAGE_NAME:$GITHUB_SHA" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
        env:
          DOCKER_BUILDKIT: 1

      - name: Pull Docker image
        if: github.event_name != 'pull_request'
        run: docker pull "$IMAGE_NAME:$GITHUB_SHA"

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.17.0
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{ github.sha }}"
          format: "sarif"
          exit-code: 0
          output: "${{ env.TRIVY_SARIF }}"

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: "${{ env.TRIVY_SARIF }}"
