name: Build backend

on:
  pull_request:
    branches: [master]

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}/backend'

jobs:
  docker_build:
    name: "Build with Docker"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache
        run: |
          cd backend
          docker build \
            --cache-from "$IMAGE_NAME" \
            -t "$IMAGE_NAME:$GITHUB_SHA" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
        env:
          DOCKER_BUILDKIT: 1
