name: Cypress end-to-end tests

on:
  pull_request:
    branches: [master]

permissions:
  packages: write
  actions: read

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}/backend'
  TAG: ${{ github.sha }}

jobs:
  build-backend:
    name: 'Build backend'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
          files_ignore: |
            backend/.gitignore
            backend/.env.example
          since_last_remote_commit: true

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo "any_changed = ${{ steps.changed-files.outputs.any_changed }}"

      - name: Set up Docker Buildx
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache and push to registry
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v5
        with:
          context: 'backend'
          push: 'true'
          tags: '${{ env.IMAGE_NAME }}:${{ env.TAG }}'
          cache-from: '${{ env.IMAGE_NAME }}:latest'
          cache-to: 'type=inline'

  cypress-e2e-tests:
    name: 'Cypress end-to-end tests'
    runs-on: ubuntu-latest
    needs: [build-backend]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files, frontend
        id: changed-files-frontend
        uses: tj-actions/changed-files@v44
        with:
          files: |
            frontend/**
            .github/workflows/cypress-e2e-test.yml
          files_ignore: |
            *.md
            *.png
            *.ico
            *.svg
            *.test.tsx
            frontend/.gitignore
            frontend/.env.example
          since_last_remote_commit: true

      - name: List all changed files, frontend
        run: |
          for file in ${{ steps.changed-files-frontend.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo "any_changed = ${{ steps.changed-files-frontend.outputs.any_changed }}"

      - name: Get changed files, backend
        id: changed-files-backend
        uses: tj-actions/changed-files@v44
        with:
          files: |
            backend/**
          files_ignore: |
            backend/.gitignore
            backend/.env.example
          since_last_remote_commit: true

      - name: List all changed files, backend
        run: |
          for file in ${{ steps.changed-files-backend.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
          echo "any_changed = ${{ steps.changed-files-backend.outputs.any_changed }}"

      - name: Start backend
        if: steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-backend.outputs.any_changed == 'true'
        run: |
          cd backend
          docker compose up &
        env:
          BACKEND_TAG: ${{ steps.changed-files-backend.outputs.any_changed == 'true' && github.sha || 'latest' }}

      - name: Setup frontend dependencies
        uses: ./.github/actions/pnpm
        with:
          working-directory: 'frontend'

      - name: Force Cypress install, workaround
        run: |
          cd frontend
          pnpm cypress install

      - name: Run Cypress end-to-end tests
        if: steps.changed-files-frontend.outputs.any_changed == 'true' || steps.changed-files-backend.outputs.any_changed == 'true'
        uses: cypress-io/github-action@v6.7.0
        with:
          working-directory: 'frontend'
          install-command: 'pnpm i'
          build: 'pnpm build'
          start: 'pnpm start'
          wait-on: 'http://localhost:3000, http://localhost:8080/status'
          config: 'video=false'
          browser: 'firefox'
        env:
          NEXTAUTH_SECRET: 'very-secret-string-123'

      - name: Upload Cypress screenshots (only on failure)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: 'cypress-screenshots'
          path: 'frontend/cypress/screenshots'
