name: Deploy backend
on:
  push:
    branches: [master]

permissions:
  packages: write
  actions: read

env:
  IMAGE: 'ghcr.io/${{ github.repository }}/backend:latest'

jobs:
  docker_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache and push to registry
        run: |
          cd backend
          docker build \
            --cache-from "$IMAGE" \
            -t "$IMAGE" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
          docker push "$IMAGE"
        env:
          DOCKER_BUILDKIT: 1

  deploy:
    runs-on: ubuntu-latest
    needs: [docker_push]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start containers on droplet
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DROPLET_ADDRESS }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            export ADMIN_KEY=${{ secrets.ADMIN_KEY }}
            echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u bakseter --password-stdin
            docker pull $IMAGE
            cd 531/backend
            git pull
            docker compose -f docker-compose.prod.yaml stop
            docker compose -f docker-compose.prod.yaml up -d --no-build
