name: Lint, format & test

on:
  pull_request:
    branches: [master]

jobs:
  lint_format_test:
    name: 'Lint, format & test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup frontend dependencies
        uses: ./.github/actions/pnpm
        with:
          working-directory: 'frontend'

      - name: Run linter
        run: pnpm lint
        working-directory: frontend

      - name: Run prettier check
        run: pnpm prettier -w "../**/*.{ts,tsx,js,jsx,mjs,css,json,md,yaml}"
        working-directory: frontend

      - name: Run tests
        run: pnpm vitest run
        working-directory: frontend
