name: Deploy backend

on:
  push:
    branches: [master]
    paths:
      ['backend/**', 'terraform/**', '.github/workflows/terraform-deploy.yaml']

env:
  IMAGE_NAME: 'ghcr.io/${{ github.repository }}/backend'

jobs:
  docker_push:
    name: 'Build with Docker and push to registry'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache and push to registry
        uses: docker/build-push-action@v4
        with:
          push: 'true'
          tags: '${{ env.IMAGE_NAME }}:latest,${{ env.IMAGE_NAME}}:${{ github.sha }}'
          cache-from: 'type=registry,ref=${{ env.IMAGE_NAME }}:latest'
          cache-to: 'type=inline'
          context: 'backend'

  scan_image:
    name: 'Scan image with Trivy'
    runs-on: ubuntu-latest
    needs: [docker_push]
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      TRIVY_SARIF: 'trivy.sarif'
    steps:
      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@0.19.0
        with:
          image-ref: '${{ env.IMAGE_NAME }}:${{ github.sha }}'
          format: 'sarif'
          exit-code: '0'
          output: ${{ env.TRIVY_SARIF }}

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ env.TRIVY_SARIF }}

  deploy_tf:
    name: 'Deploy to Azure Container Instances with Terraform'
    runs-on: ubuntu-latest
    needs: [docker_push]
    permissions:
      contents: read
    env:
      TF_CLOUD_ORGANIZATION: 'bakseter'
      TF_WORKSPACE: '531-prod'
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_revision_suffix: '"${{ github.sha }}"'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Terraform configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: './terraform'

      - name: Create Terraform run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply Terraform changes
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: 'Applying changes from GitHub Actions, commit ${{ github.sha }}'
