name: Deploy backend

on:
  push:
    branches: [master]
    paths: ["backend/**", "terraform/**", ".github/workflows/deploy.yaml"]

permissions:
  packages: write
  actions: read

env:
  IMAGE_NAME: "ghcr.io/${{ github.repository }}/backend"

jobs:
  docker_push:
    name: "Build with Docker and push to registry"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend with cache and push to registry
        run: |
          cd backend
          docker build \
            --cache-from "$IMAGE_NAME" \
            -t "$IMAGE_NAME:latest" \
            -t "$IMAGE_NAME:${{ github.sha }}" \
            --build-arg BUILDKIT_INLINE_CACHE=1 \
            .
          docker push "$IMAGE_NAME" --all-tags
        env:
          DOCKER_BUILDKIT: 1

  deploy_tf:
    name: "Deploy to Azure Container Instances with Terraform"
    runs-on: ubuntu-latest
    needs: [docker_push]
    permissions:
      contents: read
    env:
      TF_CLOUD_ORGANIZATION: "bakseter"
      TF_WORKSPACE: "531-prod"
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_revision_suffix: "\"${{ github.sha }}\""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Terraform configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.2.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: "./terraform"

      - name: Create Terraform run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.2.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply Terraform changes
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.2.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Applying changes from GitHub Actions ${{ github.sha }}"
