name: Terraform format

on:
  pull_request:
    branches: [master]

defaults:
  run:
    working-directory: terraform

jobs:
  terraform_format:
    name: 'Terraform format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check format
        run: terraform fmt -check -recursive
